### ISSUE TITLE
AMO broken link fix and proposal as official extension

### ISSUE THREAD

**Issue by erotavlas-turbo** [gitladen7/protonmail-webextension#1]
Hi,
this extension is great. First of all, can you fix the [broken link](https://github.com/gitladen7/protonmail-extension) on the homepage of the extension on [AMO](https://addons.mozilla.org/en-US/firefox/addon/protonmail/)?
Second, I just opened an [feature request](https://github.com/ProtonMail/WebClient/issues/163#issue-516528990) on protonMail github page. Could you contact them in order to improve the extension according to their developing conduct and to propose it as official protonMail extension?
Thank you

**Comment by gitladen7** [comment]
Hello, 

Thanks for the report. I have fixed the broken link.

Regards

**Comment by User486375** [comment]
The link to this GitHub at the top of the context menu when right clicking the Chrome extension is also broken.
