### ISSUE TITLE
Missing feature: mailto protocol handler registration

### ISSUE THREAD

**Issue by ballo** [gitladen7/protonmail-webextension#2]
The biggest pain in the ass about ProtonMail is the lack of a mailto: handler. 

Yes, I know that ProtonMail fails to provide a link to compose an email, otherwise I could fix this myself merely by changing the Chromium protocol handler settings.

There is an unofficial api which may help:
https://github.com/justinkalland/protonmail-api

**Comment by ballo** [comment]
Does your API provide a method for composing a new email within the ProtonMail session window?

**Comment by gitladen7** [comment]
Hello,

Not at the moment, but I guess it would be a nice feature to have. I'll try to add it today.

Regards

**Comment by gitladen7** [comment]
Just released 1.8.0 with this feature, to enable it you have to click the "register as mailto: protocol handler" on account settings. You can test it on the links on https://github.com/gitladen7/protonmail-webextension/wiki/mailto:-test-links

**Comment by ballo** [comment]
I'll give it a try!

**Comment by ballo** [comment]
OK, I compiled and installed the Chrome extension, but it didn't register a protocol handler.

**Comment by gitladen7** [comment]
Did you enable it on the account settings? like on https://github.com/gitladen7/protonmail-webextension/wiki/Account-Settings#register-as-mailto-protocol-handler

**Comment by ballo** [comment]
Oh, now it works. I was going to mumble something about navigator.registerProtocolHandler but you got it.

Works great! Should I wait until it's in the store before singing its praises on social media?

**Comment by gitladen7** [comment]
yeah, better wait :). I have already submitted it to Chrome store but it's still "Pending Review". It's live in Firefox though.

**Comment by ballo** [comment]
Cool, I'l watch this space :)

Thanks again
