### ISSUE TITLE
Notifications not opening session

### ISSUE THREAD

**Issue by ballo** [gitladen7/protonmail-webextension#3]
Notifications generated by ProtonMail lead to the web session when clicked, but notifications from the plugin dismiss with no action. 

I'll disable notifications until this issue is solved; then I'll try them again and see if they work any better. (not a major problem except this kinda makes the notifications generated by the plugin kinda annoying and pointless)

**Comment by gitladen7** [comment]
What operating system are you using? Works on my machine. This is the code that handles it: https://github.com/gitladen7/protonmail-webextension/blob/master/src/background/services/notificationService.ts#L26-L37

**Comment by ballo** [comment]
Mac Catalina. 

I don't have the protonmail code to compare. gmail works fine, too. hm

**Comment by ballo** [comment]
OK, I think I figured it out. While the protonmail notification happens when the session has new mail, the plugin notification happens before the session has new mail and thus there is no email to display yet

**Comment by gitladen7** [comment]
I see. Does it work fine if the ProtonMail tab is closed when you click on the notification?

For the case when the tab is already opened I guess that the extension could reload it so the mail is loaded.

**Comment by ballo** [comment]
Oops, scratch that. I for the protonmail notification first (it was ready to load) and then got the extension notification and clicking on the extension notification did NOT open the email like the protonmail notification would.

**Comment by ballo** [comment]
To be clear the tab was open and visible, which is how I know the email was in the inbox unread. The protonmail notifications work; the extension ones simply do not.

**Comment by gitladen7** [comment]
oh, ok, that was missing. Just pushed a fix: https://github.com/gitladen7/protonmail-webextension/commit/177a419c0c368c63a620611d122f19f421be0201

For now it will reload the tab (which is a bit annoying), I'll try to make it nagivate to the email without reloading the tab later.

**Comment by gitladen7** [comment]
after https://github.com/gitladen7/protonmail-webextension/commit/6630bbd04d139e34411404886815de9157752fef it should not reload anymore.

**Comment by ballo** [comment]
Dumb question: do I have to use git update for small updates form github, or can I still download the zip

**Comment by gitladen7** [comment]
if you cloned the repository you can run `git pull` to pull latest commit, otherwise you have to download the zip again.

**Comment by ballo** [comment]
Sorry for the delay but I wanted to be fairly certain: the notifications work properly now (pulled from git)

**Comment by ballo** [comment]
So, FYI if an email ends up in the spam folder the notification shows but clicking on it fails to open the spam folder. Most likely true with any non-inbox folder.
